#ifndef CPPDATASTRUCTURE_GLOBAL_H
#define CPPDATASTRUCTURE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CPPDATASTRUCTURE_LIBRARY)
#  define CPPDATASTRUCTURESHARED_EXPORT Q_DECL_EXPORT
#else
#  define CPPDATASTRUCTURESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CPPDATASTRUCTURE_GLOBAL_H
