var annotated =
[
    [ "BArray", "classBArray.html", "classBArray" ],
    [ "BinaryNode", "classBinaryNode.html", "classBinaryNode" ],
    [ "BinaryTree", "classBinaryTree.html", "classBinaryTree" ],
    [ "BNode", "classBNode.html", "classBNode" ],
    [ "BTree", "classBTree.html", "classBTree" ],
    [ "CircularList", "classCircularList.html", "classCircularList" ],
    [ "CPPDataStructure", "classCPPDataStructure.html", "classCPPDataStructure" ],
    [ "DoubleCircularList", "classDoubleCircularList.html", "classDoubleCircularList" ],
    [ "DoubleIterator", "classDoubleIterator.html", "classDoubleIterator" ],
    [ "DoubleList", "classDoubleList.html", "classDoubleList" ],
    [ "DoubleListAdapter", "classDoubleListAdapter.html", "classDoubleListAdapter" ],
    [ "DoubleNode", "classDoubleNode.html", "classDoubleNode" ],
    [ "IIterator", "classIIterator.html", "classIIterator" ],
    [ "IList", "classIList.html", "classIList" ],
    [ "InverseIterator", "classInverseIterator.html", "classInverseIterator" ],
    [ "IOrdinateList", "classIOrdinateList.html", "classIOrdinateList" ],
    [ "List", "classList.html", "classList" ],
    [ "Node", "classNode.html", "classNode" ],
    [ "Queue", "classQueue.html", "classQueue" ],
    [ "SimpleIterator", "classSimpleIterator.html", "classSimpleIterator" ],
    [ "SimpleListAdapter", "classSimpleListAdapter.html", "classSimpleListAdapter" ],
    [ "Stack", "classStack.html", "classStack" ]
];